name: Test and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_and_deploy:
    name: Test and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Install prerequisites
        run: npm install -g @google/clasp ava

      - name: Install packages
        run: npm install

      - name: Create credentials
        run: echo "$CREDENTIALS" > ~/.clasprc.json
        shell: bash
        env:
          CREDENTIALS: ${{secrets.CREDENTIALS}}

      - name: Push Clasp project changes
        run: clasp push --force
